googleAnalytics = "G-5RZBH288ST"

baseURL = "https://FortinetCloudCSE.github.io/k8s-101-workshop"
languageCode = 'en-us'
title = 'K8s Beginner Workshop'

defaultContentLanguage = "en"

theme = ["hugo-theme-relearn"]

metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "false"
uglyurls = "true"
enableEmoji = true

[params]
  description = "Fortinet FortiWeb ZTNA and FortiSOAR Workshop on Azure"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false

  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  landingPageUrl = "UserRepo"
  # Change default color scheme with a variant
  # Fortinet specific variants are: "Workshop", "UseCase", "Demo", "Spotlight", "FortinetSilver", "FortinetTeal".  These change the top left logo background & add Text under the Logo
  # For added variants, please contact fortinetcloudcse@fortinet.com
  themeVariant = "Workshop"

  #Optional, By Default, the logo banner will match the Text from themeVariant Above
  # If you would like to change the primary logo banner text, uncommenet logoBannerText Parameter and set to desired text.
  #logoBannerText="Custom Logo Banner"

  # Optional: If you'd like additional logo sub text/descriptions, use logoBannerSubText Parameter.  leave empty string to omit: ""
  #logoBannerSubText="sample sub-banner text"



[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i>Kubernetes Admin Guide "
url = "https://kubernetes.io/docs/concepts/overview/#why-you-need-kubernetes-and-what-can-it-do"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i>AKS documentation "
url = "https://learn.microsoft.com/en-us/azure/aks/"
weight = 22

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i>Kubectl Quick Reference "
url = "https://kubernetes.io/docs/reference/kubectl/quick-reference/"
weight = 23

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i>FortiGate Kubernetes Connector "
url = "https://docs.fortinet.com/document/fortigate-private-cloud/7.4.0/kubernetes-administration-guide/736375/about-fortigate-vm-and-kubernetes"
weight = 24

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i>Fortiweb Ingress Controller "
url = "https://docs.fortinet.com/document/fortiweb/7.4.1/ingress-controller-installation-guide/742835/fortiweb-ingress-controller-overview"
weight = 25


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    hrefTargetBlank = true
